services:
  app:
    build: .
    container_name: spring-java21-dev
    ports:
      - "8080:8080"
      - "5006:5005"
    volumes:
      - .:/app
      - maven-cache:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET_KEY=7f68902513f596a79e70783422079013f99e846059c4378f456860012903730a
    stdin_open: true
    tty: true

volumes:
  maven-cache: